# Generated by Django 5.2.3 on 2025-07-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_video_likes_remove_video_watch_later_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
